### ISSUE TITLE
DataFusion tests fail under Windows

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#226]
We temporarily disabled `datafusion` test group under Widows. Cause of the issue should be investigated.
CC @zaychenko-sergei

**Comment by s373r** [comment]
There is also a problem observed when running datafustion on Windows in `test_rest_api_request_dataset_tail()` E2E test

In all likelihood caused by this PR:  https://github.com/apache/arrow-rs/pull/5830

```
024-07-29T17:13:57.6943178Z thread 'tokio-runtime-worker' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\url-2.5.2\src\lib.rs:3028:5:
2024-07-29T17:13:57.6943333Z to_file_path() failed to produce an absolute Path
2024-07-29T17:13:57.6943409Z stack backtrace:
2024-07-29T17:13:57.6943538Z    0: std::panicking::begin_panic<ref$<str$> >
2024-07-29T17:13:57.6943850Z              at /rustc/8337ba9189de188e2ed417018af2bf17a57d51ac\library\std\src\panicking.rs:730
2024-07-29T17:13:57.6943974Z    1: url::file_url_segments_to_pathbuf_windows
...
```

(c) https://github.com/kamu-data/kamu-cli/actions/runs/10149308526/job/28063955909#step:9:9273
