### ISSUE TITLE
Output formatting fails for some GIS data

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#701]
### Describe the bug

The [`ca.vancouver.opendata.property.block-outlines`](https://github.com/kamu-data/kamu-contrib/blob/master/ca.vancouver.opendata/property/block-outlines/ca.vancouver.opendata.property.block-outlines.yaml) contrib dataset is using Apache Sedona to re-project data. The schema that this results in currently cannot be processed by kamu's output CSV / JSON formatters.

### Steps To Reproduce

1. Init and ingest the linked dataset
2. Run `kamu tail ca.vancouver.opendata.property.block-outlines --output-format json`

### Current Behavior

```
thread 'main' panicked at src/utils/data-utils/src/data/format.rs:530:13:
not implemented: Array-of-Arrays encoding is not yet supported for List(Field { name: "item", data_type: Float64, nullable: true, dict_id: 0, dict_is_ordered: false, metadata: {} })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1a648b397dedc98ada3dd3360f6d661ec2436c56/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/1a648b397dedc98ada3dd3360f6d661ec2436c56/library/core/src/panicking.rs:72:14
   2: kamu_data_utils::data::format::encoder_for_json
             at /home/smikhtoniuk/Work/projects/kamu/kamu-cli/src/utils/data-utils/src/data/format.rs:530:13
   3: <kamu_data_utils::data::format::JsonLineDelimitedWriter<W> as kamu_data_utils::data::format::RecordsWriter>::write_batch
             at /home/smikhtoniuk/Work/projects/kamu/kamu-cli/src/utils/data-utils/src/data/format.rs:234:27
   4: kamu_data_utils::data::format::RecordsWriter::write_batches
             at /home/smikhtoniuk/Work/projects/kamu/kamu-cli/src/utils/data-utils/src/data/format.rs:28:13
   5: <kamu_cli::commands::tail_command::TailCommand as kamu_cli::commands::Command>::run::{{closure}}
             at /home/smikhtoniuk/Work/projects/kamu/kamu-cli/src/app/cli/src/commands/tail_command.rs:90:9
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/1a648b397dedc98ada3dd3360f6d661ec2436c56/library/core/src/future/future.rs:124:9
   7: kamu_cli::app::run::{{closure}}::{{closure}}::{{closure}}
             at /home/smikhtoniuk/Work/projects/kamu/kamu-cli/src/app/cli/src/app.rs:183:35
   8: kamu_cli::app::run::{{closure}}
             at /home/smikhtoniuk/Work/projects/kamu/kamu-cli/src/app/cli/src/app.rs:199:34
   9: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  10: tokio::runtime::coop::with_budget
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
  11: tokio::runtime::coop::budget
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
  12: tokio::runtime::park::CachedParkThread::block_on
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  13: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  15: tokio::runtime::context::runtime::enter_runtime
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  16: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  17: tokio::runtime::runtime::Runtime::block_on
             at /home/smikhtoniuk/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  18: kamu_cli::main
             at /home/smikhtoniuk/Work/projects/kamu/kamu-cli/src/app/cli/src/main.rs:15:18
  19: core::ops::function::FnOnce::call_once
             at /rustc/1a648b397dedc98ada3dd3360f6d661ec2436c56/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Expected Behavior

The parquet schema of the dataset is:
```
offset INT64,
op INT32,
system_time TIMESTAMP_MILLIS,
event_time TIMESTAMP_MILLIS,
geo_point_2d STRUCT<
  list STRUCT<
    item DOUBLE,
  >,
>,
geometry STRING,
```

Formatter chokes on nested structs / lists which is nice to fix.

But also it's not clear to me where `geo_point_2d` is coming from as `preprocess` query should only output `geometry`. We should understand the behavior of `EsriShapefile` ingest and Sedona.

`kamu inspect query ca.vancouver.opendata.property.block-outlines` also returns an empty result ... as if the preprocess query is never applied.

### kamu system info

```sh
appVersion: 0.189.1
buildTimestamp: 2024-06-30T01:33:03.503020676Z
gitDescribe: v0.188.2-16-gbbee1101
gitSha: bbee1101943673678908127ba3857455d4e37320
gitCommitDate: 2024-06-28
gitBranch: master
rustcSemver: 1.78.0-nightly
rustcChannel: nightly
rustcHostTriple: x86_64-unknown-linux-gnu
rustcCommitSha: 1a648b397dedc98ada3dd3360f6d661ec2436c56
cargoTargetTriple: x86_64-unknown-linux-gnu
cargoFeatures: default,rust_embed,web_ui
cargoOptLevel: '0'
```

**Comment by sergiimk** [comment]
Resolved by #839
